[versions]
dagger = "2.44"
gdx = "1.11.0"
nexus-publish = "1.3.0"
spotless = "6.10.0"
[libraries]
dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger"}
dagger-gwt = { module = "com.google.dagger:dagger-gwt", version.ref = "dagger"}
gdx-core = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish"}
